erDiagram
    Roles ||--o{ RolPermisos : "tiene"
    Permisos ||--o{ RolPermisos : "asignado en"
    Roles ||--o{ Usuarios : "clasifica"
    Usuarios |o--o| Medicos : "inicia sesión como"
    Especialidades ||--o{ Medicos : "agrupa"
    Pacientes ||--o{ Citas : "solicita"
    Medicos ||--o{ Citas : "atiende"
    Pacientes ||--o{ Historial : "posee"
    Medicos ||--o{ Historial : "redacta"

    Roles { int IdRol PK
        varchar NombreRol UK }
    Permisos { int IdPermiso PK
        varchar NombrePermiso UK }
    RolPermisos { int IdRol PK,FK
        int IdPermiso PK,FK }
    Usuarios { int IdUsuario PK
        varchar Usuario UK
        varchar Clave "BCrypt"
        varchar NombreCompleto
        int IdRol FK
        bit Activo }
    Especialidades { int IdEspecialidad PK
        varchar NombreEspecialidad UK }
    Medicos { int IdMedico PK
        varchar Nombre
        varchar Telefono
        varchar Correo
        int IdEspecialidad FK
        int IdUsuario FK "puede ser NULL" }
    Pacientes { int IdPaciente PK
        varchar Nombre
        varchar DUI
        date FechaNacimiento
        varchar Genero
        varchar Telefono
        varchar Direccion }
    Citas { int IdCita PK
        int IdPaciente FK
        int IdMedico FK
        date Fecha
        varchar Hora
        varchar Motivo
        varchar Estado }
    Historial { int IdHistorial PK
        int IdPaciente FK
        int IdMedico FK
        datetime Fecha
        varchar Diagnostico
        varchar Tratamiento }
    Bitacora { int IdBitacora PK
        varchar Usuario
        varchar Accion
        datetime Fecha }
