<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Vista</RootNamespace>
    <AssemblyName>Vista</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <StartupObject>Vista.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modelos\Modelos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Data" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Dashboard\frmDashboard.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Dashboard\frmInicio.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmBitacora.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmCitas.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmEspecialidades.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmHistorial.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmMedicos.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmPacientes.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmPermisos.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Gestion\frmUsuarios.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Login\frmLogin.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
