<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ClinicaMedica</RootNamespace>
    <AssemblyName>ClinicaMedica</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <!-- Encriptación de contraseñas -->
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <!-- Conexión a SQL Server -->
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <!-- Lectura de la cadena de conexión desde App.config -->
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
  </ItemGroup>

</Project>
