<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Modelos</RootNamespace>
    <AssemblyName>Modelos</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <!-- Librería para encriptar contraseñas -->
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <!-- Permite compilar aunque no esté instalado el paquete de .NET Framework 4.8 -->
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Data" />
  </ItemGroup>

</Project>
